<?php
/**
 * CoreApiTest
 * PHP version 5
 *
 * @category Class
 * @package  FincraDeveloperApi
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

namespace FincraDeveloperApi\Api;

use \FincraDeveloperApi\Configuration;
use \FincraDeveloperApi\ApiClient;
use \FincraDeveloperApi\ApiException;
use \FincraDeveloperApi\ObjectSerializer;

/**
 * CoreApiTest Class Doc Comment
 *
 * @category Class
 * @package  FincraDeveloperApi
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CoreApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for getBankcode
     *
     * Get Bank code
     *
     */
    public function test_getBankcode() {

    }
    
    /**
     * Test case for getbranchCode
     *
     * Get branch Code
     *
     */
    public function test_getbranchCode() {

    }
    
    /**
     * Test case for getadisbursementtransactionbycustomerreference
     *
     * Get a disbursement transaction by customer reference
     *
     */
    public function test_getadisbursementtransactionbycustomerreference() {

    }
    
    /**
     * Test case for getadisbursementtransactionbyreference
     *
     * Get a disbursement transaction by reference
     *
     */
    public function test_getadisbursementtransactionbyreference() {

    }
    
    /**
     * Test case for getthetransactionsforaBusiness
     *
     * Get the transactions for a Business
     *
     */
    public function test_getthetransactionsforaBusiness() {

    }
    
    /**
     * Test case for getthetransactionsforthesubAccountsofabusiness
     *
     * Get the transactions for the sub-accounts of a Business
     *
     */
    public function test_getthetransactionsforthesubAccountsofabusiness() {

    }
    
    /**
     * Test case for getatransactionforabusiness
     *
     * Get a transaction for a business
     *
     */
    public function test_getatransactionforabusiness() {

    }
    
}
